# Generated by Django 2.0.5 on 2018-05-30 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engmoduInfo',
            fields=[
                ('engmoduid', models.AutoField(primary_key=True, serialize=False, verbose_name='模块编号')),
                ('engmoduname', models.CharField(max_length=20, verbose_name='模块名称')),
                ('teacher', models.CharField(max_length=200, verbose_name='教师名称')),
                ('coursetime', models.CharField(max_length=200, verbose_name='上课时间')),
                ('limitnum', models.IntegerField(blank=True, default=1000, null=True, verbose_name='限购人数')),
                ('costfee', models.IntegerField(blank=True, default=199, null=True, verbose_name='购买金额')),
            ],
            options={
                'verbose_name': '英语模块信息',
                'verbose_name_plural': '英语模块信息',
                'db_table': 'engmoduinfo',
            },
        ),
        migrations.CreateModel(
            name='engtypeInfo',
            fields=[
                ('engtypeid', models.AutoField(primary_key=True, serialize=False, verbose_name='类别编号')),
                ('engtypename', models.CharField(max_length=200, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '英语类别信息',
                'verbose_name_plural': '英语类别信息',
                'db_table': 'engtypeinfo',
            },
        ),
        migrations.CreateModel(
            name='everbuyInfo',
            fields=[
                ('everbuyid', models.AutoField(primary_key=True, serialize=False, verbose_name='已购编号')),
                ('buytime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 30, 20, 50, 45, 740674), null=True)),
                ('engmoduid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qingye.engmoduInfo', verbose_name='英语模块名称')),
            ],
            options={
                'verbose_name': '已购课程',
                'verbose_name_plural': '已购课程',
                'db_table': 'everbuyinfo',
            },
        ),
        migrations.CreateModel(
            name='roleInfo',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False, verbose_name='角色编号')),
                ('rolename', models.CharField(max_length=20, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '角色信息',
                'verbose_name_plural': '角色信息',
                'db_table': 'roleinfo',
            },
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户名称')),
                ('username', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('phonenum', models.CharField(max_length=20, verbose_name='电话号码')),
                ('emailaddr', models.CharField(max_length=200, verbose_name='邮箱地址')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qingye.roleInfo', verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='videoInfo',
            fields=[
                ('videoid', models.AutoField(primary_key=True, serialize=False, verbose_name='视频编号')),
                ('videoname', models.CharField(max_length=200, verbose_name='视频名称')),
                ('videopath', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('engmoduid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qingye.engmoduInfo', verbose_name='模块名称')),
            ],
            options={
                'verbose_name': '学习视频信息',
                'verbose_name_plural': '学习视频信息',
                'db_table': 'videoinfo',
            },
        ),
        migrations.AddField(
            model_name='everbuyinfo',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qingye.userInfo', verbose_name='用户名称'),
        ),
        migrations.AddField(
            model_name='engmoduinfo',
            name='engtypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qingye.engtypeInfo', verbose_name='类别名称'),
        ),
    ]
