# Generated by Django 2.0.5 on 2018-06-05 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everbuyinfo',
            name='buytime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 5, 12, 40, 46, 790058), null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='videopath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
